###
# Author: V. COGNAT
# Affiliation: IBMP - CNRS
# Aim: A simple Snakemake workflow to process tRNA annotation.
# Description: Config file for all data path
# Date: Wed March 18 CET 2020
###

## Project dir ##
workdir: "~/tRNAflow"

## Path to split_tRNA.R prog (change the path to your ananconda3)
splitRNA: "~/opt/anaconda3/envs/trnaflow/lib/R/library/tRNAscanImport/split_tRNA.R"

## Genome description file
genome_file: "Genome_description.txt"